# Generated by Django 6.0.6 on 2026-07-06 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_referral_codes(apps, schema_editor):
    """Give every existing user a referral code so their invite links work."""
    import secrets
    User = apps.get_model('accounts', 'User')
    alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
    used = set(User.objects.exclude(referral_code__isnull=True)
               .values_list('referral_code', flat=True))
    for user in User.objects.filter(referral_code__isnull=True):
        code = ''.join(secrets.choice(alphabet) for _ in range(8))
        while code in used:
            code = ''.join(secrets.choice(alphabet) for _ in range(8))
        used.add(code)
        user.referral_code = code
        user.save(update_fields=['referral_code'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_bonus_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_referral_codes, noop),
    ]
