# Generated by Django 6.0.6 on 2026-06-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown on listing page (max 300 chars)', max_length=300)),
                ('body', models.TextField(help_text='Full post content. HTML is supported.')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 chars). Defaults to excerpt if empty.', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='Social share image (1200×630 recommended)', null=True, upload_to='blog/og/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
