# Generated by Django 6.0.6 on 2026-07-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_update_order_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProviderStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('successful', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('provider', 'product', 'country')},
            },
        ),
    ]
