# Generated by Django 6.0.6 on 2026-07-06 02:10

from django.db import migrations, models


def mark_pending_topups(apps, schema_editor):
    """
    Existing top-ups whose description still says 'pending' were never credited.
    Keep them PENDING so a late Paystack webhook/verify can still confirm them,
    instead of the new default COMPLETED silently locking them out.
    """
    Transaction = apps.get_model('orders', 'Transaction')
    Transaction.objects.filter(
        type='CREDIT', description__icontains='pending'
    ).update(status='PENDING')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_retry_count_providerstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='COMPLETED', max_length=10),
        ),
        migrations.RunPython(mark_pending_topups, noop),
    ]
