# Generated by Django 6.0.6 on 2026-07-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('VIRTUAL_NUMBER', 'Virtual Number'), ('OTP_VERIFICATION', 'OTP Verification'), ('TEMPORARY_EMAIL', 'Temporary Email'), ('VPN', 'VPN Subscription'), ('ESIM', 'eSIM Package'), ('RESIDENTIAL_PROXY', 'Residential Proxy'), ('BULK_SMS', 'Bulk SMS'), ('PHONE_LOOKUP', 'Phone Number Lookup'), ('AIRTIME', 'Airtime / Data Top-up'), ('GIFT_CARD', 'Gift Card'), ('UTILITY', 'Utility Bill Payment')], max_length=20),
        ),
    ]
